- src/components/Order.js
- src/components/OrderStatus.js
Reverts onitsoft/nexchange-open-client-react#96
> Revert "Adjust order statuses on order progress bar too."

- src/components/Order.js
- src/components/OrderStatus.js
Reverts onitsoft/nexchange-open-client-react#97
> Re-enable new status codes

- src/sitemap.xml
Still lacks faq and support pages. And I don't know if it is in the right folder.
> WIP sitemap

- src/actions/index.js
Check if referral code has value in order to filter fiat currencies of the list.
> Check if white label to filter fiat currencies.

- src/actions/index.js
- src/containers/CountDown.js
- src/containers/RecentOrders.js
- src/containers/order/Order.js
Added a moment locale for easy translations, so user/admin will be able to easy change language for their translations
>  localization for Nexchange

- public/locales/en/translations.json
- src/components/Order/OrderMain/OrderState/OrderFiatModals/KYCModalTier0/KYCModalTier0.jsx
- src/components/Order/OrderMain/OrderState/OrderPaymentFiat/OrderPaymentFiat.js
- src/locales/en/translations.json
> Explain tier 1 ID selfie

- src/components/Home/Team/Team.js
Please remove ASAP, Justas asked 5 times for this already.
> Remove Karolis and Justas as team members

- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinInput.js
- src/components/MinMax/MinMax.js
- src/css/_general.scss
Status: WIP
Background (user-story):
1. User should be able to click min and max values to auto fill order value
Implementation:
1. MinMax and CoinInput logic work 
2. CSS tweak
Tests:
WIP
> Order - Clickable Min Max Values

- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinInput.js
- src/components/MinMax/MinMax.js
Just changed function name
From: assignMinMaxValue
To: setValue
Seems way more cleaner and makes sense
> Feature/order clickable min max values - Changed function name

- package.json
updated webpack dev server to 3.1.11
> Remove vulnerable version of webpack dev server

- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinInput.js
- src/components/Home/Hero/ExchangeWidget/CoinSwitch/CoinSwitch.js
- src/components/Home/Hero/ExchangeWidget/CoinSwitch/CoinSwitch.scss
- src/components/Home/Hero/ExchangeWidget/ExchangeWidget.js
Status: [WAITING FOR REVIEW]
Background (user-story):
1. User wants to easily switch coins (within the same pair)
Implementation:
1. Created coin switch component and styles
2. Added component to parent 
3  Added coin switch logic
4. Added valid pair verification
> Added coin switch button (switch coin within the same pair)

- src/actions/index.js
- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinSelector/CoinSelector.js
Status: WAITING FOR REVIEW
Background:
1. When a user chooses the same coin in the receive/deposit pair, they should switch
There was an error because the pairs variable in the COIN_SELECT reducer was undefined. Changed some logic in order to get access to the pairs state variable in that reducer
> Fixed coin switch when selecting same coin

- src/components/Header/LanguagePicker/LanguagePicker.js
Status: WAITING FOR REVIEW
Background:
1. Menu bar language links should be lower case ?lang=ru instead of ?lang=RU
> Lowercase lang param url on lang change

- src/components/Header/Header.js
Status: WAITING FOR REVIEW
Background:
1. Changed "About us" menu bar link from url change to scroll to
> About us link should be scroll to

- .storybook/webpack.config.shared.js
- src/stories/order-crypto.stories.js
- src/stories/order-fiat.stories.js
- src/stories/order-full-crypto.stories.js
Status: WAITING FOR REVIEW
Fixed broken storybook build
1. Storybook webpack config updated
2. Updated stories css paths
> Fixed broken storybook build

- src/components/Header/Header.scss
> Hidden non visible menu item (ICO)

- src/components/Home/Hero/ExchangeWidget/CoinSwitch/CoinSwitch.scss
Coinswitch button style tweak for sm devices
> Style tweak for sm devices

- src/components/Header/LanguagePicker/LanguagePicker.js
Language picker was redirecting for the main page. Now it stays in the same page
> Now language picker doesn't change page

- src/components/Home/Hero/ExchangeWidget/CoinSwitch/CoinSwitch.js
> Removed unnecessary code

- src/components/Home/Hero/ExchangeWidget/ExchangeWidget.js
- src/components/Home/Hero/ExchangeWidget/WalletAddress/WalletAddress.js
- src/components/Order/OrderMain/OrderState/OrderLinks/OrderLinks.js
When all order details are filled. Auto focus place order button
> Repeat order -> Auto focus place order button

- src/components/Header/Header.js
Compare rates link should be scroll to
> Compare rates link should be scroll to

- src/actions/index.js
- src/components/Header/FAQ/QuestionAnswer/QuestionAnswer.js
- src/components/Header/Header.js
- src/components/Header/Support/Support.js
- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinInput.js
- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinSelector/CoinSelector.js
- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinSelector/CoinsDropdown/CoinsDropdown.js
- src/components/Home/Hero/ExchangeWidget/CoinSwitch/CoinSwitch.js
- src/components/Home/Hero/ExchangeWidget/ExchangeWidget.js
- src/components/Home/Hero/ExchangeWidget/WalletAddress/AddressHistory/AddressHistory.js
- src/components/Home/ICO/ICO.js
- src/components/Order/Order.js
- src/components/Order/OrderCta/OrderReferrals/OrderReferrals.js
- src/components/Order/OrderMain/OrderState/OrderPaymentFiat/OrderPaymentTemplateFiat/DesktopNotifications/DesktopNotifications.js
- Migrated from google analyitcs universal api to google tag manager
- Added coin dropdown search (Not found) event
> Google Analytics Refactoring

- src/actions/index.js
Select random pair when Invalid pair url param
> Select random pair when Invalid pair url param

- src/components/Home/Hero/ExchangeWidget/WalletAddress/WalletAddress.js
Address History - Show only the most recent entry for each address
> Address History - Show only the most recent entry for each address

- src/components/Home/Hero/ExchangeWidget/WalletAddress/WalletAddress.js
Coin Switch - Fixed invalid address error message
> Coin Switch - Fixed invalid address error message

- src/components/Order/OrderMain/OrderState/OrderInitial/OrderInitialFiat/OrderInitialFiat.js
Moved safecharge payment to iframe instead of opening new tab
> Moved safecharge payment to iframe

- src/components/Home/Hero/OrderBookWidget/DepositModal/DepositModal.js
- src/components/Home/Hero/OrderBookWidget/LimitOrderForm/LimitOrderForm.js
- src/components/Home/Hero/OrderBookWidget/MyOrders/MyOrders.js
- src/components/Home/Hero/OrderBookWidget/MyOrders/MyOrders.scss
- src/components/Home/Hero/OrderBookWidget/OrderBookWidget.js
- src/components/Home/Hero/OrderBookWidget/OrderBookWidget.scss
- src/components/Home/Hero/OrderBookWidget/OrderDepth/OrderDepth.js
- src/utils/generateDepth.js
Order Creation + Deposit Modal + My Orders + Tweaks + Fixes + Improvements
> Order Creation + Deposit Modal + My Orders + Tweaks + Fixes + Improvements

- src/actions/index.js
- src/components/Home/Hero/OrderBookWidget/DepositModal/DepositModal.js
- src/components/Home/Hero/OrderBookWidget/MyOrders/MyOrders.js
- src/components/Home/Hero/OrderBookWidget/OrderDepth/OrderDepthItem/OrderDepthItem.js
- src/components/Home/Hero/OrderBookWidget/OrderDepth/OrderDepthItem/OrderDepthItem.scss
- src/css/_general.scss
- src/reducers/reducer_order_book.js
> UI/UX work + Tweaks + Fixes

- src/components/Home/Hero/OrderBookWidget/LimitOrderForm/LimitOrderForm.js
- src/components/Home/Hero/OrderBookWidget/OrderDepth/OrderDepthItem/OrderDepthItem.js
- src/config.js
> Order Book - Fixes

- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinSelector/CoinSelector.js
- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinSelector/CoinsDropdown/CoinsDropdown.scss
- src/components/Home/Hero/OrderBookWidget/OrderBookWidget.js
- src/components/Home/Hero/OrderBookWidget/OrderDepth/OrderDepth.js
> Order Book - Tweaks and Fixes 

- src/components/Header/Header.js
- src/components/Home/Home.js
- src/index.js
> FAQ Page - Fixes

- src/config.js
This commit connects the frontend to an older instance of the API in order to allow our activate customers to continue enjoying our services within their integrations with our API.
[EXAMPLE]
Status: [BLOCKED][WIP][WAITING FOR REVIEW]
Background (user-story):
1. Bob wants to buy Bitcoins directly to his phone, since he does not have an external wallet.
Implementation:
1. Wallet service using local storage
2. Cold Signing
3. Export key using BIP39 memorable phrases
Unit tests included:
1. Wallet generation
2. Cold signing
3. Key impporting and exporting
Integration tests:
1. Make an order to a local wallet
> Connecting the frontend to the old API

- src/components/WhiteLabel/PriceTable/index.js
Pricing table update to display 'N/A' for community plan pricing and features
> add 'N/A' for community features

- src/components/Pair/Articles/Articles.js
- src/components/Pair/Articles/get-articles.query.js
Update query object and dates on articles in per pair exchange
> fix article dates

- src/components/Ellipses/Ellipse.js
- src/components/FooterNext/Footer.js
- src/components/Header/Header.js
- src/components/Order/OrderMain/OrderState/OrderOpen/OrderOpen.js
- src/components/Order/OrderMain/PnlTracking/PnlTracking.js
- src/components/Pair/Articles/Articles.js
- src/components/Pair/PriceChart/index.js
- src/components/WhiteLabel/FAQ2/index.js
- src/components/WhiteLabel/VideoCard/index.js
UX and mobile for white label pages
> codestyle cleaup

- src/components/WhiteLabel/SupportedAssets/index.js
- src/components/misc/ToTop/index.js
Remove smooth scrolling when navigating - it activates the Bounce animations too early.
> fix scroll to top and animation on white label

- src/components/WhiteLabel/SupportedAssets/index.js
- src/pages/WhiteLabelSEO/index.js
- src/pages/WhiteLabelSEO/topics/index.js
Reverts onitsoft/nexchange-open-client-react#634
> Revert "Fix/remove wl anim"

- public/locales/en/translations.json
- src/components/Footer/index.js
- src/components/WhiteLabel/SupportedAssets/index.js
- src/pages/WhiteLabelSEO/index.js
- src/pages/WhiteLabelSEO/topics/index.js
updated footer and removed white label bounce animations
> updated footer to requirements

- src/actions/index.test.js
- src/components/Order/OrderMain/OrderState/OrderPaymentCrypto/__snapshots__/OrderPaymentCrypto.test.js.snap
tests began failing after updated api urls.
> updated api url to fix test

- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinInput.js
fix coin input overriding value
> improve check for coin input update values

- public/locales/en/translations.json
- src/components/Accounts/ForgotPassword/reset.js
- src/components/Accounts/SignIn/SignIn.js
- src/components/Accounts/SignUp/SignUp.js
- src/components/Footer/index.js
- src/components/Header/Header.js
- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinInput.js
- src/index.js
Reverts onitsoft/nexchange-open-client-react#660
> Revert "Dev"

- src/components/Home/Hero/ExchangeWidget/ExchangeWidget.js
removed [Simple] and [Advanced] on ExchangeWidget
> removed advanced and simple modes from main funnel

- scripts/test.js
- src/components/Header/__snapshots__/Header.test.js.snap
- src/components/Home/Hero/ExchangeWidget/ExchangeWidget.js
- src/components/Order/OrderCoinsProcessed/OrderCoinsProcessed.js
- src/components/Order/OrderCoinsProcessed/OrderCoinsProcessed.test.js
- src/components/Pair/Hero/ExchangeWidget/ExchangeWidget.js
- src/components/Pair/Hero/ExchangeWidget/WalletAddress/WalletAddress.js
- src/css/_fonts.scss
- src/index.js
Status: [WAITING FOR REVIEW]
Fixes: fixed font-faces in CSS.
> fixed font faces

- config/webpack.config.prod.js
- package-lock.json
- package.json
- public/index.html
- public/locales/en/translations.json
- src/actions/index.test.js
- src/components/FAQ/FAQ.js
- src/components/Footer/Footer.js
- src/components/Home/About/About.js
- src/components/Home/Hero/ExchangeWidget/CoinInput/CoinSelector/CoinSelector.test.js
- src/components/Home/Testimonials/Testimonials.js
- src/components/Home/Testimonials/Testimonials.scss
- src/components/Order/Order.js
- src/components/Order/OrderCoinsProcessed/OrderCoinProcessed/OrderCoinProcessed.test.js
- src/components/Order/OrderCoinsProcessed/OrderCoinsProcessed.test.js
- src/components/Order/OrderMain/OrderState/OrderPaymentCrypto/__snapshots__/OrderPaymentCrypto.test.js.snap
- src/components/Privacy/Privacy.js
- src/components/TermsConditions/TermsConditions.js
- src/components/Transitioning/Transitioning.js
- src/config.js
- src/index.js
- Fix API URL because it was pointing to api.nexchange.io domain
- Replace uglify webpack plugin with terser
- fix lint errors
- also made some copy changes as per client feedback
> fix errors on dragondex

- src/components/Accounts/ForgotPassword/ForgotPassword.js
- src/components/Accounts/ForgotPassword/request.js
- src/components/Accounts/ForgotPassword/reset.js
- src/components/Accounts/SignIn/SignIn.js
- src/components/Accounts/SignUp/SignUp.js
- src/components/Footer/index.js
- src/components/Header/Header.js
- src/components/Order/OrderMain/OrderState/OrderLinks/OrderLinks.js
- src/components/Order/OrderMain/OrderState/OrderSuccess/OrderSuccess.js
- src/components/Pair/Hero/CoinPrices/CoinPrices.js
- src/index.js
- Adds language to url path (if missing)
- fixes White Label link in footer
- fixes Links in Sign Up / SIgn In Page
- fixes Forgot password page
- When redirecting from root (/  to /lang), url params were not getting passed to /lang route, now fixed.
> Router fix

- src/components/Order/OrderMain/OrderState/OrderPaymentFiat/OrderPaymentFiat.js
- yarn.lock
KYC showing twice error fixed 
Thanks to Punit for the cue.
> KYC text showing twice error fixed

- src/components/Order/OrderCoinsProcessed/OrderCoinProcessed/OrderCoinProcessed.jsx
- src/components/Order/OrderCoinsProcessed/OrderCoinsProcessed.js
- src/components/Order/OrderMain/OrderState/OrderInitial/OrderInitial.js
- src/components/Order/OrderMain/OrderState/OrderInitial/OrderInitialCrypto/OrderInitialCrypto.js
- src/components/Order/OrderMain/OrderState/OrderInitial/OrderInitialFiat/OrderInitialFiat.js
- src/components/Order/OrderMain/OrderState/OrderState.js
- src/utils/useCountdown.js
- fix infinite orders bug
- show order inital (without timer) after payment deadline
- replace cancelled screen with expired
> fixes infinite order bug after order expiry

- public/index.html
- src/components/FAQ/FAQ.scss
- src/components/FAQ2/FAQ.scss
- src/components/Header/Header.scss
- src/components/Home/Hero/Hero.scss
- src/components/Home/ICO/CountdownItem/CountdownItem.scss
- src/components/Home/ICO/ICO.scss
- src/components/Home/Testimonials/Testimonials.scss
- src/components/Pair/Hero/Hero.scss
- src/components/WhiteLabel/FAQ2/FAQ.scss
- src/components/WhiteLabel/KeyFeatures/KeyFeatures.scss
- src/css/_cryptocoins.scss
- src/css/_fonts.scss
- src/css/_general.scss
this PR fixes issue of font loading twice on front-end and also adds a fallback for custom font
> fix font preloading and add font fallback

- src/components/Order/OrderCoinsProcessed/OrderCoinsProcessed.js
- src/components/Order/OrderCoinsProcessed/OrderCoinsProcessed.test.js
[WAITING FOR REVIEW]
Description: removed unnecessary comments.
> removed comments

- public/index.html
updated hotjar tracking code as asked by Nathan
> update hotjar tracking code

- src/__tests__/reducers/reducer_wallet.test.js
- src/actions/index.js
- src/actions/types.js
- src/components/Order/Order.js
- src/components/Order/OrderCoinsProcessed/OrderCoinProcessed/OrderCoinProcessed.jsx
- src/components/Order/OrderCoinsProcessed/OrderCoinProcessed/WalletAddress/WalletAddress.js
- src/components/Order/OrderMain/OrderState/OrderExpired/OrderExpired.js
- src/reducers/reducer_wallet.js
This PR fixes delay with address update after s/he submits wallet address.
> fix address update delay
